# Generated by Django 3.2.5 on 2021-08-03 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSummary',
            fields=[
            ],
            options={
                'verbose_name': 'User Summary',
                'verbose_name_plural': 'User Summary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.customuser',),
        ),
    ]
